default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  host: localhost
  port: 5432
  pool: 5
  database: censusaur
  username: maebeale
  password:

development:
  <<: *default

test:
  <<: *default
  database: censusaur_test

staging:
  <<: *default

production:
  <<: *default
